export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  salePrice?: number;
  image: string;
  images: string | string[];
  category: string;
  materials?: string[];
  careInstructions?: string;
  tags?: string[];
  sizes?: any[];
  colors?: string[];
  stock: number;
  isNew?: boolean;
  createdAt: string;
  reviews?: any[];
  rating?: number;
}

export let products: Product[] = [
  {
    id: "prod-1",
    name: "Áo Hoodie Aura Mẫu A",
    description: "Một thiết kế áo khoác vượt thời gian, chiếc áo hoodie mang đậm phong cách trẻ trung năng động. Được làm từ chất liệu vải thun nỉ cao cấp, mềm mại và giữ ấm tốt.\n\nThích hợp cho những buổi dạo phố, đi học, hay đi chơi cùng bạn bè.",
    price: 650000,
    salePrice: 450000,
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=1887&auto=format&fit=crop",
    images: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=1887&auto=format&fit=crop",
    category: "Áo Khoác",
    materials: ["100% Cotton Nỉ", "Dày dặn"],
    careInstructions: "Giặt máy ở chế độ nhẹ nhàng với nước lạnh.\nKhông sử dụng hóa chất tẩy rửa mạnh.\nPhơi trong bóng râm, tránh ánh nắng trực tiếp.\nỦi ở nhiệt độ thấp.",
    tags: ["Mùa đông", "Năng động", "Trẻ trung"],
    sizes: [{name: "S", stock: 10}, {name: "M", stock: 15}, {name: "L", stock: 5}],
    colors: ["Đen", "Xám"],
    stock: 30,
    createdAt: new Date().toISOString(),
    reviews: [
      { id: "rev-1", name: 'Nguyễn Thị A', rating: 5, date: '10/10/2023', content: 'Chất liệu vải rất đẹp, mềm mại và đứng form. Đường may tỉ mỉ, mặc lên tôn dáng.' },
      { id: "rev-2", name: 'Trần B', rating: 4, date: '05/10/2023', content: 'Màu sắc giống hình, tuy nhiên giao hàng hơi chậm một chút. Sản phẩm đáng tiền.' }
    ]
  },
  {
    id: "prod-2",
    name: "Quần Jogger Aura Mẫu B",
    description: "Quần jogger dáng suông ôm nhẹ vừa vặn, thiết kế tối giản dễ phối đồ. Lưng thun co giãn thoải mái mang đến trải nghiệm tuyệt vời cả ngày dài.",
    price: 550000,
    image: "https://images.unsplash.com/photo-1552902865-b72c031ac5ea?q=80&w=1964&auto=format&fit=crop",
    images: "https://images.unsplash.com/photo-1552902865-b72c031ac5ea?q=80&w=1964&auto=format&fit=crop",
    category: "Quần",
    materials: ["Vải thun gân", "Co giãn 4 chiều"],
    careInstructions: "Giặt tay hoặc giặt máy.\nKhông ngâm quá lâu.\nPhơi khô tự nhiên.",
    tags: ["Thể thao", "Thoải mái"],
    sizes: [{name: "M", stock: 20}, {name: "L", stock: 10}],
    colors: ["Xám", "Be"],
    stock: 30,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-3",
    name: "Áo Sơ Mi Lụa C",
    description: "Sơ mi lụa tơ tằm mềm mại, thấm hút mồ hôi tốt. Kiểu dáng công sở hiện đại, thích hợp cho nhiều hoàn cảnh.",
    price: 850000,
    salePrice: 650000,
    image: "https://images.unsplash.com/photo-1596755094514-f87e32f85e2c?q=80&w=1888&auto=format&fit=crop",
    images: "https://images.unsplash.com/photo-1596755094514-f87e32f85e2c?q=80&w=1888&auto=format&fit=crop",
    category: "Áo Sơ Mi",
    materials: ["Lụa tơ tằm"],
    careInstructions: "Giặt khô hoặc giặt tay với nước lạnh.\nKhông vắt mạnh.",
    tags: ["Công sở", "Thanh lịch"],
    sizes: [{name: "S", stock: 15}, {name: "M", stock: 20}],
    colors: ["Trắng", "Xanh Nhạt"],
    stock: 35,
    isNew: true,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-4",
    name: "Đầm Dự Tiệc D",
    description: "Thiết kế đầm hai dây xẻ tà quyến rũ, tôn vóc dáng. Chất liệu vải lụa satin cao cấp.",
    price: 1200000,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=1983&auto=format&fit=crop",
    images: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=1983&auto=format&fit=crop",
    category: "Đầm",
    materials: ["Lụa Satin"],
    careInstructions: "Giặt khô.",
    tags: ["Dự tiệc", "Quyến rũ"],
    sizes: [{name: "S", stock: 5}, {name: "M", stock: 8}],
    colors: ["Đỏ", "Đen"],
    stock: 13,
    isNew: true,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-5",
    name: "Túi Xách Da Cao Cấp",
    description: "Túi xách da thật với đường may thủ công tỉ mỉ. Phụ kiện không thể thiếu cho các quý cô.",
    price: 2500000,
    salePrice: 1990000,
    image: "https://images.unsplash.com/photo-1584916201218-f4242ceb4809?q=80&w=1915&auto=format&fit=crop",
    images: "https://images.unsplash.com/photo-1584916201218-f4242ceb4809?q=80&w=1915&auto=format&fit=crop",
    category: "Phụ kiện",
    materials: ["Da bò nguyên tấm"],
    careInstructions: "Lau chùi bằng khăn mềm.\nSử dụng kem dưỡng da chuyên dụng.",
    tags: ["Túi xách", "Sang trọng"],
    sizes: [{name: "One Size", stock: 10}],
    colors: ["Nâu", "Đen"],
    stock: 10,
    isNew: true,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-6",
    name: "Kính Mát Thời Trang",
    description: "Kính mát gọng kim loại chống tia UV400, thiết kế cổ điển phù hợp với mọi khuôn mặt.",
    price: 450000,
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=2080&auto=format&fit=crop",
    images: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=2080&auto=format&fit=crop",
    category: "Phụ kiện",
    materials: ["Kim loại", "Polycarbonate"],
    careInstructions: "Lau kính bằng khăn chuyên dụng.",
    tags: ["Mùa hè", "Du lịch"],
    sizes: [{name: "One Size", stock: 50}],
    colors: ["Vàng", "Bạc"],
    stock: 50,
    isNew: true,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-7",
    name: "Chân Váy Chữ A Aura",
    description: "Chân váy chữ A dáng xòe nhẹ nhàng quyến rũ, thiết kế thời thượng tôn vòng eo thon gọn. Phù hợp phối đồ đi làm, đi chơi hay dự tiệc nhẹ.",
    price: 480000,
    salePrice: 350000,
    image: "https://images.unsplash.com/photo-1583496661160-fb48862c484f?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1583496661160-fb48862c484f?q=80&w=1000&auto=format&fit=crop"],
    category: "Váy",
    materials: ["Vải thun sạn", "Mềm nhẹ"],
    careInstructions: "Giặt tay nhẹ nhàng.",
    tags: ["Xuân Hè", "Thanh lịch"],
    sizes: [{name: "S", stock: 12}, {name: "M", stock: 15}, {name: "L", stock: 8}],
    colors: ["Đen", "Be"],
    stock: 35,
    isNew: true,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-8",
    name: "Áo Blazer Linen Cổ Điển",
    description: "Thiết kế blazer phom dáng suông rộng rãi hiện đại, chất liệu vải linen tự nhiên mát mẻ và thấm hút mồ hôi tốt. Hoàn hảo cho phong cách smart-casual công sở.",
    price: 1100000,
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=1000&auto=format&fit=crop"],
    category: "Áo Khoác",
    materials: ["100% Linen tự nhiên"],
    careInstructions: "Giặt nhẹ bằng tay, tránh vắt mạnh. Là ủi ở nhiệt độ trung bình.",
    tags: ["Mùa hè", "Công sở"],
    sizes: [{name: "S", stock: 10}, {name: "M", stock: 10}, {name: "L", stock: 10}],
    colors: ["Trắng", "Be"],
    stock: 30,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-9",
    name: "Đầm Dạ Hội Lụa Satin",
    description: "Đầm thiết kế dáng dài cổ yếm quyến rũ, chất liệu lụa satin cao cấp óng ả, rủ nhẹ tôn dáng ngọc ngà của các quý cô trong các bữa tiệc đêm sang trọng.",
    price: 1850000,
    salePrice: 1390000,
    image: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1496747611176-843222e1e57c?q=80&w=1000&auto=format&fit=crop"],
    category: "Đầm",
    materials: ["Lụa Satin cao cấp"],
    careInstructions: "Khuyến khích giặt khô để bảo vệ bề mặt lụa.",
    tags: ["Sang trọng", "Dự tiệc"],
    sizes: [{name: "S", stock: 5}, {name: "M", stock: 5}],
    colors: ["Đỏ", "Xanh Navy"],
    stock: 10,
    isNew: true,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-10",
    name: "Quần Tây Ống Suông Aura",
    description: "Quần tây phom suông rộng cạp cao hack dáng, che khuyết điểm chân cực tốt. Đường ly quần ủi đứng phom tạo vẻ ngoài chuyên nghiệp, chỉn chu.",
    price: 680000,
    image: "https://images.unsplash.com/photo-1509551388413-e18d0ac5d495?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1509551388413-e18d0ac5d495?q=80&w=1000&auto=format&fit=crop"],
    category: "Quần",
    materials: ["Vải tuyết mưa cao cấp"],
    careInstructions: "Giặt máy bình thường.",
    tags: ["Công sở", "Hằng ngày"],
    sizes: [{name: "S", stock: 15}, {name: "M", stock: 20}, {name: "L", stock: 15}],
    colors: ["Đen", "Trắng"],
    stock: 50,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-11",
    name: "Áo Thun Cotton Organic",
    description: "Áo thun cơ bản phom ôm vừa vặn, dệt từ sợi cotton hữu cơ mềm mịn thân thiện với làn da và bền màu. Dễ dàng mix-match với mọi trang phục.",
    price: 320000,
    image: "https://i.pinimg.com/736x/08/84/77/0884777f06ecaf836fadd5d620585696.jpg",
    images: ["https://i.pinimg.com/736x/08/84/77/0884777f06ecaf836fadd5d620585696.jpg"],
    category: "Áo",
    materials: ["100% Organic Cotton"],
    careInstructions: "Có thể giặt máy.",
    tags: ["Hằng ngày", "Năng động"],
    sizes: [{name: "S", stock: 30}, {name: "M", stock: 30}, {name: "L", stock: 20}],
    colors: ["Trắng", "Đen"],
    stock: 80,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-12",
    name: "Giày Cao Gót Mũi Nhọn Suede",
    description: "Đôi giày cao gót 7cm chất liệu da lộn mềm mại sang trọng, đệm lót êm chân giúp phái đẹp tự tin sải bước cả ngày dài mà không mỏi.",
    price: 980000,
    salePrice: 790000,
    image: "https://images.unsplash.com/photo-1596609548086-85bbf8ddb6b9?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1596609548086-85bbf8ddb6b9?q=80&w=1000&auto=format&fit=crop"],
    category: "Giày",
    materials: ["Da lộn tự nhiên"],
    careInstructions: "Lau sạch bằng bàn chải chuyên dụng cho da lộn.",
    tags: ["Sự kiện", "Thanh lịch"],
    sizes: [{name: "36", stock: 10}, {name: "37", stock: 10}, {name: "38", stock: 10}],
    colors: ["Đen", "Đỏ"],
    stock: 30,
    isNew: true,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-13",
    name: "Áo Cardigan Dệt Kim Mỏng",
    description: "Áo khoác cardigan len dệt kim mỏng nhẹ nhàng, co giãn tốt, thích hợp khoác ngoài trong thời tiết se lạnh hoặc thu đông.",
    price: 490000,
    salePrice: 390000,
    image: "https://images.unsplash.com/photo-1614975058789-41316d0e2e9c?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1614975058789-41316d0e2e9c?q=80&w=1000&auto=format&fit=crop"],
    category: "Áo Khoác",
    materials: ["Len dệt kim cao cấp"],
    careInstructions: "Giặt tay nhẹ, tránh vắt xoắn mạnh.",
    tags: ["Thu Đông", "Nhẹ nhàng"],
    sizes: [{name: "S", stock: 15}, {name: "M", stock: 15}],
    colors: ["Be", "Xanh Navy"],
    stock: 30,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-14",
    name: "Chân Váy Xếp Ly Nhỏ Aura",
    description: "Thiết kế chân váy xếp ly xòe điệu đà nữ tính, cạp cao tôn dáng. Vải sạn cát giữ ly tốt, không nhăn sau khi giặt.",
    price: 520000,
    image: "https://images.unsplash.com/photo-1578587018452-892bacefd3f2?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1578587018452-892bacefd3f2?q=80&w=1000&auto=format&fit=crop"],
    category: "Váy",
    materials: ["Cát Hàn cao cấp"],
    careInstructions: "Ủi ở nhiệt độ thấp.",
    tags: ["Mùa hè", "Nữ tính"],
    sizes: [{name: "S", stock: 10}, {name: "M", stock: 10}],
    colors: ["Hồng Nhạt", "Đen"],
    stock: 20,
    isNew: true,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-15",
    name: "Đầm Cổ Chữ V Sang Trọng",
    description: "Đầm dài cổ chữ V quyến rũ, eo chun ôm tôn dáng nhẹ nhàng. Chất liệu cao cấp mát lạnh phù hợp đi chơi hè hoặc dạo phố.",
    price: 1350000,
    salePrice: 990000,
    image: "https://images.unsplash.com/photo-1612336307429-8a898d10e223?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1612336307429-8a898d10e223?q=80&w=1000&auto=format&fit=crop"],
    category: "Đầm",
    materials: ["Voan Hàn Quốc"],
    careInstructions: "Giặt tay nhẹ nhàng.",
    tags: ["Mùa hè", "Dạo phố"],
    sizes: [{name: "S", stock: 8}, {name: "M", stock: 12}],
    colors: ["Hoa Nhí", "Be"],
    stock: 20,
    isNew: true,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-16",
    name: "Quần Kaki Dáng Baggy",
    description: "Quần kaki phom rộng baggy trẻ trung năng động, chất kaki dày dặn bền đẹp. Rất hợp mix cùng áo phông cơ bản.",
    price: 590000,
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=1000&auto=format&fit=crop"],
    category: "Quần",
    materials: ["100% Kaki Cotton"],
    careInstructions: "Giặt máy thoải mái.",
    tags: ["Năng động", "Hằng ngày"],
    sizes: [{name: "S", stock: 15}, {name: "M", stock: 15}, {name: "L", stock: 10}],
    colors: ["Be", "Xanh Rêu"],
    stock: 40,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-17",
    name: "Áo Sơ Mi Linen Cổ Trụ",
    description: "Áo sơ mi dáng rộng cổ trụ thoải mái, chất vải linen tự nhiên dày dặn nhưng thoáng mát. Sự lựa chọn tuyệt vời cho ngày hè mát mẻ.",
    price: 450000,
    image: "https://images.unsplash.com/photo-1596755094514-f87e32f85e2c?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1596755094514-f87e32f85e2c?q=80&w=1000&auto=format&fit=crop"],
    category: "Áo",
    materials: ["100% Linen tự nhiên"],
    careInstructions: "Giặt nhẹ bằng tay, tránh dùng hóa chất tẩy.",
    tags: ["Mùa hè", "Tối giản"],
    sizes: [{name: "S", stock: 10}, {name: "M", stock: 20}, {name: "L", stock: 10}],
    colors: ["Be", "Trắng"],
    stock: 40,
    isNew: true,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-18",
    name: "Đầm Voan Hoa Nhí Aura",
    description: "Đầm thiết kế voan mỏng mát lót trong mềm mại, họa tiết hoa nhí nữ tính. Eo chun co giãn tốt đem lại cảm giác thoải mái khi diện dạo phố.",
    price: 890000,
    salePrice: 690000,
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=1000&auto=format&fit=crop"],
    category: "Đầm",
    materials: ["Voan hoa nhí"],
    careInstructions: "Nên bỏ túi giặt nếu giặt máy.",
    tags: ["Mùa hè", "Nữ tính"],
    sizes: [{name: "S", stock: 15}, {name: "M", stock: 15}],
    colors: ["Hoa nhí xanh", "Hoa nhí hồng"],
    stock: 30,
    isNew: true,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-19",
    name: "Quần Jeans Nữ Ôm Cạp Cao",
    description: "Quần jeans skinny chất liệu bò co giãn bốn chiều cực tốt, nâng mông tôn dáng eo cạp cao thời thượng. Dễ dàng mix cùng mọi kiểu áo dáng croptop.",
    price: 650000,
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=1000&auto=format&fit=crop"],
    category: "Quần",
    materials: ["Jeans co giãn tốt"],
    careInstructions: "Không giặt chung đồ trắng sáng ở lần đầu.",
    tags: ["Hằng ngày", "Cơ bản"],
    sizes: [{name: "26", stock: 10}, {name: "27", stock: 15}, {name: "28", stock: 10}],
    colors: ["Xanh đậm", "Xanh nhạt"],
    stock: 35,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-20",
    name: "Áo Khoác Phao Ấm Áp",
    description: "Thiết kế áo phao lông vũ siêu nhẹ giữ nhiệt tối đa, phom rộng phong cách Hàn Quốc trẻ trung. Thích hợp đi du lịch nơi lạnh giá.",
    price: 1800000,
    salePrice: 1450000,
    image: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=1000&auto=format&fit=crop"],
    category: "Áo Khoác",
    materials: ["Lông vũ siêu nhẹ"],
    careInstructions: "Khuyến khích giặt khô.",
    tags: ["Thu Đông", "Ấm áp"],
    sizes: [{name: "M", stock: 10}, {name: "L", stock: 10}],
    colors: ["Đen", "Kem"],
    stock: 20,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-21",
    name: "Mũ Cói Thắt Nơ Điệu Đà",
    description: "Mũ cói rộng vành đan thủ công tỉ mỉ, đính dây nơ đen tinh tế. Phụ kiện che nắng hoàn hảo tuyệt vời cho kỳ nghỉ đi biển hè.",
    price: 290000,
    image: "https://images.unsplash.com/photo-1572420144376-3be83bb40ab6?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1572420144376-3be83bb40ab6?q=80&w=1000&auto=format&fit=crop"],
    category: "Phụ kiện",
    materials: ["Sợi cói tự nhiên"],
    careInstructions: "Tránh ngâm nước.",
    tags: ["Mùa hè", "Du lịch"],
    sizes: [{name: "One Size", stock: 25}],
    colors: ["Cói tự nhiên"],
    stock: 25,
    isNew: true,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-22",
    name: "Giày Cao Gót Quai Hậu",
    description: "Đôi giày cao gót 5cm gót vuông vững chãi quai hậu thanh mảnh lịch thiệp, đệm lót siêu êm đi lại nhẹ nhàng không đau mỏi chân.",
    price: 850000,
    image: "https://images.unsplash.com/photo-1562273138-f46be4ebdf33?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1562273138-f46be4ebdf33?q=80&w=1000&auto=format&fit=crop"],
    category: "Giày",
    materials: ["Da tổng hợp mềm"],
    careInstructions: "Lau sạch bằng khăn ẩm.",
    tags: ["Công sở", "Sự kiện"],
    sizes: [{name: "36", stock: 10}, {name: "37", stock: 15}, {name: "38", stock: 10}],
    colors: ["Đen", "Kem"],
    stock: 35,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-23",
    name: "Áo Blazer Phom Lửng",
    description: "Thiết kế blazer phom lửng croptop năng động trẻ trung, tạo điểm nhấn cá tính thanh lịch khi mix cùng chân váy chữ A hoặc quần ống rộng.",
    price: 820000,
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=1000&auto=format&fit=crop"],
    category: "Áo Khoác",
    materials: ["Kaki thun đứng phom"],
    careInstructions: "Ủi nhẹ ở nhiệt độ vừa phải.",
    tags: ["Thanh lịch", "Công sở"],
    sizes: [{name: "S", stock: 10}, {name: "M", stock: 10}],
    colors: ["Nâu đất", "Đen"],
    stock: 20,
    isNew: true,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-24",
    name: "Đầm Bodycon Thun Gân",
    description: "Đầm ôm body thun gân tăm co giãn tốt cực kỳ tôn dáng, tay dài thanh lịch cuốn hút. Hoàn hảo diện đi dự tiệc nhẹ hay hẹn hò tối.",
    price: 750000,
    salePrice: 550000,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=1000&auto=format&fit=crop"],
    category: "Đầm",
    materials: ["Thun tăm gân co giãn"],
    careInstructions: "Tránh giặt bằng chất tẩy mạnh.",
    tags: ["Hẹn hò", "Sang trọng"],
    sizes: [{name: "S", stock: 10}, {name: "M", stock: 10}],
    colors: ["Đen", "Đỏ Rượu"],
    stock: 20,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-25",
    name: "Chân Váy Denim Cá Tính",
    description: "Chân váy denim phom ôm cá tính có xẻ tà nhẹ phá cách, chất vải jeans dày dặn đứng phom trẻ trung năng động thích hợp dạo phố.",
    price: 520000,
    image: "https://images.unsplash.com/photo-1583496661160-fb48862c484f?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1583496661160-fb48862c484f?q=80&w=1000&auto=format&fit=crop"],
    category: "Váy",
    materials: ["Vải denim dày"],
    careInstructions: "Giặt lộn trái chân váy.",
    tags: ["Năng động", "Dạo phố"],
    sizes: [{name: "S", stock: 12}, {name: "M", stock: 15}],
    colors: ["Xanh Indigo"],
    stock: 27,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-26",
    name: "Áo Hoodie Nỉ Bông In Chữ",
    description: "Áo hoodie chất nỉ bông dày dặn ấm áp cho ngày đông lạnh, phom dáng rộng thoải mái in chữ cá tính phong cách đường phố.",
    price: 680000,
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=1000&auto=format&fit=crop"],
    category: "Áo Khoác",
    materials: ["Nỉ bông dày"],
    careInstructions: "Giặt máy bình thường.",
    tags: ["Đường phố", "Năng động"],
    sizes: [{name: "M", stock: 20}, {name: "L", stock: 20}],
    colors: ["Xám", "Đen"],
    stock: 40,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-27",
    name: "Quần Short Lửng Kaki",
    description: "Quần đùi short kaki lửng thiết kế cạp cao thoải mái dễ phối, năng động hợp diện những ngày hè đi dã ngoại picnic hay dạo mát.",
    price: 350000,
    image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?q=80&w=1000&auto=format&fit=crop"],
    category: "Quần",
    materials: ["Kaki thun mềm"],
    careInstructions: "Có thể giặt máy.",
    tags: ["Mùa hè", "Dã ngoại"],
    sizes: [{name: "S", stock: 15}, {name: "M", stock: 15}],
    colors: ["Be", "Xanh quân đội"],
    stock: 30,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-28",
    name: "Đầm Suông Linen Thêu Hoa",
    description: "Đầm dáng suông rộng nhẹ thoải mái thêu họa tiết hoa nhỏ trước ngực, chất liệu linen mát lành dịu nhẹ với da nhạy cảm.",
    price: 950000,
    salePrice: 750000,
    image: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1496747611176-843222e1e57c?q=80&w=1000&auto=format&fit=crop"],
    category: "Đầm",
    materials: ["100% Linen tự nhiên"],
    careInstructions: "Giặt nhẹ nhàng.",
    tags: ["Tự nhiên", "Tối giản"],
    sizes: [{name: "S", stock: 10}, {name: "M", stock: 15}],
    colors: ["Trắng ngà", "Xanh nhạt"],
    stock: 25,
    isNew: true,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-29",
    name: "Túi Đeo Chéo Mini Da Mềm",
    description: "Túi đeo chéo mini thiết kế gọn gàng đựng điện thoại son phấn, chất da nhân tạo mềm mại khóa kéo mạ vàng sang trọng.",
    price: 390000,
    image: "https://images.unsplash.com/photo-1584916201218-f4242ceb4809?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1584916201218-f4242ceb4809?q=80&w=1000&auto=format&fit=crop"],
    category: "Phụ kiện",
    materials: ["Da mềm PU cao cấp"],
    careInstructions: "Lau sạch bằng khăn khô mềm.",
    tags: ["Dạo phố", "Phụ kiện"],
    sizes: [{name: "One Size", stock: 20}],
    colors: ["Nâu đất", "Đen"],
    stock: 20,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-30",
    name: "Kính Mát Phi Công Gọng Mảnh",
    description: "Kính mát chống tia cực tím UV cực tốt, dáng gọng phi công kim loại mỏng tinh xảo cá tính đẳng cấp thời trang.",
    price: 520000,
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=1000&auto=format&fit=crop"],
    category: "Phụ kiện",
    materials: ["Gọng kim loại titan"],
    careInstructions: "Tránh cọ xát mặt kính.",
    tags: ["Mùa hè", "Phụ kiện"],
    sizes: [{name: "One Size", stock: 15}],
    colors: ["Vàng kim", "Đen"],
    stock: 15,
    isNew: true,
    createdAt: new Date().toISOString(),
    reviews: []
  },
  {
    id: "prod-31",
    name: "Giày Búp Bê Thắt Nơ Đen",
    description: "Giày búp bê đế bệt thắt nơ trước nhỏ nhắn dễ thương xinh xắn, da mềm mại không cấn gót tạo cảm giác dễ chịu khi đi bộ nhiều.",
    price: 650000,
    image: "https://images.unsplash.com/photo-1596609548086-85bbf8ddb6b9?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1596609548086-85bbf8ddb6b9?q=80&w=1000&auto=format&fit=crop"],
    category: "Giày",
    materials: ["Da bóng PU"],
    careInstructions: "Lau sạch nhẹ.",
    tags: ["Hằng ngày", "Dạo phố"],
    sizes: [{name: "36", stock: 10}, {name: "37", stock: 15}, {name: "38", stock: 10}],
    colors: ["Đen"],
    stock: 35,
    createdAt: new Date().toISOString(),
    reviews: []
  }
];

export const setProducts = (newProducts: Product[]) => {
  products = newProducts;
};
